### ISSUE TITLE
老贺有把插件搬到safari的计划么？

### ISSUE THREAD

**Issue by ImaginationZ** [laohyx/electsys#1]

**Comment by gaocegege** [comment]
@laohyx 我写了一个粗糙的safari extension在[https://github.com/gaocegege/electsys-safari](https://github.com/gaocegege/electsys-safari)，感觉完善完善就可以放心使用啦～顺便问一句，[http://electsys.net/electsys/](http://electsys.net/electsys/)访问不了啦～？

**Comment by laohyx** [comment]
因为域名备案问题，我把网站关闭了。
现在也没时间维护插件了。我把你的链接放到README里吧

**Comment by gaocegege** [comment]
@laohyx 好吧，好多学弟问怎么下载选课插件，忽然发现了这个问题～

**Comment by laohyx** [comment]
我更新了readme，把你的链接加上去了。学弟需要下载的话，从README进入webstore，或者让他们安装safari/firefox版插件吧……

在 2015-01-02 09:49:26，"Gao Ce" <notifications@github.com> 写道：


@laohyx 好吧，好多学弟问怎么下载选课插件，忽然发现了这个问题～

**Comment by gaocegege** [comment]
@laohyx Get～

**Comment by at15** [comment]
@gaocegege 策策好帅!

**Comment by at15** [comment]
@gaocegege @laohyx 有可能把这两个repo合并么?

**Comment by laohyx** [comment]
我把@gaocegege 加到collaborators里了，另外@at15也接受邀请呀

**Comment by gaocegege** [comment]
@at15 可以，有很多代码重复，但就是需要一个坚韧不拔的同学来做

**Comment by laohyx** [comment]
有一个简单的办法，就是先别动具体的代码，将运行的代码剥离出来，然后就可以Port到不同浏览器了~

**Comment by gaocegege** [comment]
close via https://github.com/dyweb/electsys-safari
