### ISSUE TITLE
发布 2.4？

### ISSUE THREAD

**Issue by ComMouse** [laohyx/electsys#10]
感觉现在做的更改已经比较多了，可能需要发布一个新版本比较好？

大致的变更有：
- 在”修业查看“页面中显示所有课程的 GPA 和各小项的 GPA
- 修复小学期选课页面通识课没有高亮标注的问题
- 更新通识课列表
- 优化选课前的注意事项页面
- 由于部分代码使用 ES 6，将只支持 Chrome 49+ 版本

@laohyx @at15 @gaocegege @zackszhu @hczhcz

**Comment by at15** [comment]
先在github上发个release呗

**Comment by ComMouse** [comment]
似乎现在 Chrome 不在应用商店下的插件根本就不让安装。。不管是 crx 还是解压后的。。

**Comment by ShieLian** [comment]
开发者模式倒是可以用(跑

**Comment by zackszhu** [comment]
求发布！

**Comment by gaocegege** [comment]
=-=老学长表示发布也试用不到了，不过支持一个

**Comment by hczhcz** [comment]
=-=小鲜肉表示发布也试用不到了，不过支持一个

**Comment by laohyx** [comment]
大家好，我来发布了！
另外，我将这个插件的发布权限给了一个google group，大家快去申请加入！

https://groups.google.com/forum/#!forum/electsys

**Comment by ComMouse** [comment]
Release notes 已添加
