### ISSUE TITLE
发布 2.4.2

### ISSUE THREAD

**Issue by ComMouse** [laohyx/electsys#13]
- 增加核心课程成绩页面的 GPA 计算
- 更新通识课列表
- 在选课页面查看课程安排时可优先使用点击“查”按钮时缓存的页面（目前可能会引发其他不影响使用的小 bug）
- 修复修业查看中正在修读课程列入 GPA 计算的问题 (#11)

@ShieLian @gaocegege @at15 @laohyx

**Comment by at15** [comment]
@ComMouse 还移除了广告

**Comment by ComMouse** [comment]
广告是上一个版本弄的

**Comment by laohyx** [comment]
Done. 
另外建议把Zip包上传了（作为草稿），这样我只要点一下发布就好啦~

**Comment by ComMouse** [comment]
谢谢学长=w=
