### ISSUE TITLE
“查询绩点”和“我的成绩单”页面的bug

### ISSUE THREAD

**Issue by gousaiyang** [laohyx/electsys#14]
- "查询绩点"页面，第一次点击“全选”的时候，按钮文字没有变成“全不选”，从第二次开始才会变。这样当下面的项目已经全部选中时，上面的按钮还是“全选”；当下面的项目全部没有选中的时候，上面的按钮却是“全不选”了。状态恰好相反了，可能代码里有错误？
- “我的成绩单”页面，因为有的成绩不是数值，而是P/F制（如“通过”）或者等级制（如“A-”），这时候全选的平均分计算值就是NaN。希望可以优化一下？
- 还有一个问题，是"查询绩点"和“我的成绩单”页面共有的，就是如果先点击“全选”按钮，然后去掉一项，然后又重新选上刚才去掉的一项（通过点击行的方式，而不是再点“全选”按钮），那么现在是处于全选状态的。但插件并不能识别这种情况，“全选”按钮上面的字还是“全选”，点一次之后下面的项目也还是全选状态的。如果能够在用户每次点击一行的时候判断当前是不是已经处于全选状态，如果已经全选就把“全选”按钮的字改成“全不选”，并相应地更新按钮的行为。这样是不是会更智能一些？

**Comment by ComMouse** [comment]
已知的 bug 额，不过因为各种原因没有修。。

**Comment by at15** [comment]
头像好评，我是来打酱油的

**Comment by hczhcz** [comment]
头像有趣
