### ISSUE TITLE
16 级通识课学分和类别政策改变

### ISSUE THREAD

**Issue by ComMouse** [laohyx/electsys#15]
转自教务处 http://www.jwc.sjtu.edu.cn/web/sjtu/198392-1980000006071.htm

涉及到插件的有：
1. 通识变成五个分类了：人文、社科、自科、工程、院系通识
2. 冲抵课程列表暂时没有变化，但是 16 级手册中没有提及冲抵信息

@laohyx @ 16级的童鞋们

**Comment by ShieLian** [comment]
不知道对16级以前的没有影响。。这就很尴尬了

**Comment by at15** [comment]
....做下适配?

**Comment by ComMouse** [comment]
并看不到新页面

**Comment by ComMouse** [comment]
根据 http://www.jwc.sjtu.edu.cn/web/sjtu/198015-1980000004260.htm，16 级开始不可以冲抵了额，可能不会对插件功能有影响，冲抵提示已加上"2015级及以前“
