### ISSUE TITLE
评教模块失效

### ISSUE THREAD

**Issue by ComMouse** [laohyx/electsys#17]
由于教务处在今年还是去年改了一次版，把所有评教内容换到一页里了，原先所有的评教相关部分暂时失效了，需要修复额
- [x] “快速评教”似乎可以去掉了，现在的新页面已经很快了……
- [x] 修复“分数联动”
- [ ] 其他改进

**Comment by gaocegege** [comment]
加油

**Comment by ShieLian** [comment]
v2.5.0 chrome测试分数联动暂无bug

**Comment by gaocegege** [comment]
Thanks for your feedback

@ShieLian

**Comment by ComMouse** [comment]
实测中期评教是有 Bug 的……两个部分好像是不同的代码

**Comment by ShieLian** [comment]
@ComMouse 什么鬼。。我按正常流程走了一遍没问题。。

**Comment by ComMouse** [comment]
@ShieLian 是在点快速评教的时候会出现“分数联动”，那个按钮的意思是拖动的时候使所有行的打分同时调整

**Comment by ShieLian** [comment]
@ComMouse 你是说别的行的调整的时候也有联动的效果？

**Comment by ComMouse** [comment]
@ComMouse 对的，算一个便捷功能

**Comment by ShieLian** [comment]
@ComMouse 噫，我觉得现在这样挺好，拉那个栏调整所有分数，个别的分数想修改也不会再把所有栏的分数改掉

**Comment by ComMouse** [comment]
@ShieLian 好像现在由于改版了会有其他古怪的行为，抽空修掉好了。。

**Comment by ShieLian** [comment]
@ComMouse 是么。。我好像没发现蛤蛤

**Comment by ComMouse** [comment]
似乎并没有 bug。。。close 了

**Comment by ShieLian** [comment]
理论教学类期末评教有时候还是出现分数条卡死点不动的情况

**Comment by ComMouse** [comment]
已确认不是选课插件引发的问题…… 原先的滚动条在页面滚动后会出现坐标计算错误导致跪掉……
