### ISSUE TITLE
关于 Firefox 插件

### ISSUE THREAD

**Issue by hczhcz** [laohyx/electsys#20]
长话短说，[Firefox 插件](https://github.com/hczhcz/electsys)的代码过时了，如果还有人在用它的话，欢迎来维护。主要的维护工作是保持 content script 和这边同步，做必要的测试，以及上传给 Mozilla 做签名。

一些技术细节：目前插件只使用了 content script。`./content/init.js`会检测当前页面是不是 electsys，并装载脚本。因此，引入新的脚本后需要把它加在`./content/init.js`的列表里。另外，每次更新后，`./install.rdf`里需要修改版本号和 Firefox 的版本兼容范围。

愿意来做 collaborator 的欢迎报名 :-)

**Comment by ComMouse** [comment]
Firefox 自版本 49 开始也支持 Chrome 插件架构了，原则上改下 manifest.json 就可以用了~

**Comment by DHPO** [comment]
[Electsys++ 交大选课插件 - 版本 2.5.2 - 已火狐化.xpi.zip](https://github.com/laohyx/electsys/files/651796/Electsys.-.2.5.2.-.xpi.zip)
刚转换好的，亲测50.1.0能用

**Comment by gaocegege** [comment]
@DHPO 谢谢你的贡献，但是我想我们需要的是可以长期维护选课插件的火狐版本的同学，或者是可以把火狐版本重构下，把它合并到这个 repo 里来管理 :-)

有兴趣嘛

**Comment by ComMouse** [comment]
@gaocegege 其实可以写个脚本把 Chrome 版本的直接转换成 Firefox 的，因为差别很小……

**Comment by gaocegege** [comment]
@ComMouse 那也需要人做嘛

**Comment by DHPO** [comment]
试试[这个](https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/)
可以访问chrome的应用商店，可以自动将chrome的扩展转换为Firefox的扩展

**Comment by gaocegege** [comment]
@DHPO Thanks for your advice, we'll think about this solution.

**Comment by ComMouse** [comment]
Close? @hczhcz

**Comment by hczhcz** [comment]
See also: https://github.com/dyweb/mos/issues/9
