### ISSUE TITLE
教师评教等信息是如何获取的？

### ISSUE THREAD

**Issue by LQYMGT** [laohyx/electsys#3]
我在 ./content_script/load.js 里面的更新日志看到，与教务处的合作。那么评教信息没有更新过么？

**Comment by laohyx** [comment]
评教信息是之前抓网页数据保存下来的，并没有与JWC合作。
而且确实没有更新过。。应该是11年左右的数据……

**Comment by LQYMGT** [comment]
On Sun, Feb 15 2015 at 21:29:35 +0800, laohyx wrote:
> 评教信息是之前抓网页数据保存下来的，并没有与JWC合作。
> 而且确实没有更新过。。应该是11年左右的数据……
>

是在哪里抓取的呢？我找了一下没找到有给出评教结果的地方呢。

**Comment by laohyx** [comment]
要在合适的地方点击老师信息，然后就有老师的评教信息了。位置大约是点击时间安排后，可以看到老师吧。。
因为时间过于久远，我也只记得这些了……

**Comment by LQYMGT** [comment]
On Sun, Feb 15 2015 at 21:45:38 +0800, laohyx wrote:
> 要在合适的地方点击老师信息，然后就有老师的评教信息了。位置大约是点击时间安排后，
> 可以看到老师吧。。
> 因为时间过于久远，我也只记得这些了……

懂了，下次选课的时候我看看。
