### ISSUE TITLE
Overall GPA calculation

### ISSUE THREAD

**Issue by codeworm96** [laohyx/electsys#31]
When applying for job or master/PhD, sometimes the overall GPA is needed. However, the plugin can only calculate the GPA of one semester now. It is nice to have an overall GPA calculation feature.

**Comment by gaocegege** [comment]
说不定可以参考 https://github.com/gaocegege/electsys

我曾经实现过类似的但是没有提 PR =。= 因为太丑了

**Comment by ComMouse** [comment]
@codeworm96 已实现，功能入口在“修业查看”和“核心课程成绩”里

**Comment by ShieLian** [comment]
真快xd

**Comment by ComMouse** [comment]
@ShieLian 以前有的功能额

**Comment by at15** [comment]
@gaocegege 代码如人啊 (那我这种只写 README 的该算什么

![](http://livedoor.4.blogimg.jp/sr_cobra/imgs/1/7/176f680c.gif)

**Comment by gaocegege** [comment]
@at15 不，我只是不会写 js

**Comment by codeworm96** [comment]
棒！之前一直没有找到入口...

**Comment by at15** [comment]
@gaocegege 那么你会 PHP 么

**Comment by kdplus** [comment]
@at15 可能是偶像大师吧
