### ISSUE TITLE
关于在edge中使用插件

### ISSUE THREAD

**Issue by cihe13375** [laohyx/electsys#34]
好像按readme里面写的把source code直接加载到edge是不能用的，表现为选项默认全不勾选且不能修改；要用微软给的一个Microsoft Edge Extension Toolkit（在应用商店里面有）转置一下
转置之后功能大部分正常，就是比较烦的每次都会被提示已关闭来自未知源的扩展（解决这个好像得把插件发布到应用商店里面。。）

所以只是希望把readme改一下，或者传一个转置之后的版本上来；谢谢~

**Comment by ComMouse** [comment]
同学你好，Edge 版本可以参考其他同学提供的 Fork：

https://github.com/ZhaobangChina/ElectsysForEdge
