### ISSUE TITLE
新版chrome识别验证码似乎又失效了

### ISSUE THREAD

**Issue by sjtu-jq** [laohyx/electsys#39]
最新chrome版本 74.0.3729.157（正式版本） （64 位），识别验证码自动登陆不可用了，不知道是否是个例

**Comment by ShieLian** [comment]
嗯不是，其实上学期开始就不行了(

**Comment by sjtu-jq** [comment]
最新版本的插件在三月份更新的时候有一段时间可以用，后来再也不行了
