### ISSUE TITLE
验证码自动识别错误率较高

### ISSUE THREAD

**Issue by danyang685** [laohyx/electsys#40]
目前JAccount验证码分为以下类型：
按颜色：红色、绿色、蓝色三种颜色，目前的灰度化算法采用比例0.2989、0.5870、0.1140处理，不能很好地归一化这三种颜色，在转为单色图时灰度深浅不同。
按字母：均为小写字母，4个或5个。
按间距：总在同一高度，间距可密可疏。目前在处理间距较小的验证码时，因为没有检测到纵向空隙，造成多个字母粘连。

在正确分割的情况下，也时有识别错误。

另有一个疑问，[captcha.js](https://github.com/laohyx/electsys/blob/master/content_script/page/captcha.js)文件中绝大多数篇幅储存了神经网络的参数，这个网络是利用什么数据集和什么程序训练的？

谢谢。

**Comment by cvwc2019** [comment]
Check PR#26

**Comment by ShieLian** [comment]
Check PR #26

**Comment by danyang685** [comment]
> Check PR #26

感谢回复！但是没看到任何想要的内容。验证码识别在我的浏览器上运行毫无延迟，只是识别效果存在问题。

**Comment by ComMouse** [comment]
似乎是 JAccount 的验证码后来加了粗细和斜体导致的，之前添加相应功能的时候可能没有考虑到这些。关于具体神经网络训练的方式可以向 PR 作者 @fztfztfztfzt 了解一下，如果有余力能够帮助改进识别算法的话非常欢迎提交 PR~

**Comment by fztfztfztfzt** [comment]
貌似JAccount进行了更新，需要的数据集和训练程序以及爬取数据集的脚本都可以在[jaccount-captcha](https://github.com/fztfztfztfzt/jaccount-captcha)中找到。
有余力的话欢迎帮助改进识别算法！

**Comment by danyang685** [comment]
> 貌似JAccount进行了更新，需要的数据集和训练程序以及爬取数据集的脚本都可以在[jaccount-captcha](https://github.com/fztfztfztfzt/jaccount-captcha)中找到。
> 有余力的话欢迎帮助改进识别算法！

谢谢！我在[jaccount-captcha](https://github.com/fztfztfztfzt/jaccount-captcha)只看到了用于测试神经网络的MATLAB程序。训练、图像的预处理和分割等功能均不在此仓库内。是否另有脚本实现了这些功能，烦请确认一下？

**Comment by fztfztfztfzt** [comment]
可以参考[jaccount1](https://jeff-leaf.site/2017/03/20/%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C%E7%9A%84Javascript%E5%AE%9E%E7%8E%B0%EF%BC%9AJaccount%E9%AA%8C%E8%AF%81%E7%A0%81%E8%AF%86%E5%88%AB-chrome%E6%8F%92%E4%BB%B6/)和[jaccount2](https://jeff-leaf.site/2017/04/21/Jaccount%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C%E6%8F%92%E4%BB%B6%EF%BC%9A%E7%AE%80%E5%8D%952%E5%B1%82ANN%E6%A8%A1%E5%9E%8B/)
