### ISSUE TITLE
求支持Microsoft Edge

### ISSUE THREAD

**Issue by taoyouh** [laohyx/electsys#8]

**Comment by ComMouse** [comment]
同学你好，由于人手关系，我们在短时间内可能无法实现对 Edge 的全面支持。但是，由于 Edge 的插件架构是和 Chrome 相通的，理论上做一些小的修改就可以移植到 Edge 上了。如果有精力的话也欢迎帮忙移植到 Edge 上~

经测试，现在的版本在 Edge 上应该使跑得起来的，不过可能不会不少的 bug。关于如何在 Edge 中导入插件，敬请参考这个页面：https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/extensions/guides/adding-and-removing-extensions/

**Comment by zackszhu** [comment]
刚才看了一下，在选课之外的GPA计算没问题，等选课开发之后我再看看选课里面有没有问题

**Comment by gaocegege** [comment]
re @zackszhu 
Edge插件是写成了一个新的repo还是一个branch，有办法merge到master么
ref https://github.com/laohyx/electsys/issues/1#issuecomment-236427259

**Comment by zackszhu** [comment]
@gaocegege 因为是同一个架构的，所以可以直接用这个repo。 @ComMouse 已经更新了一些设置，现在可以直接load的

**Comment by gaocegege** [comment]
re @zackszhu 
棒，那可以现在提交一个WIP的PR？

**Comment by zackszhu** [comment]
re @gaocegege 不用啊，我的意思是目前的代码可以直接用，我并没有改什么。。

**Comment by gaocegege** [comment]
喔，soga 😄
