### ISSUE TITLE
重构 PLAN

### ISSUE THREAD

**Issue by gaocegege** [laohyx/electsys#9]
https://github.com/laohyx/electsys/blob/master/content_script/page/lesson.js#L706:#L708

可读性不是很好，应该有更好的方式吧

**Comment by at15** [comment]
你开issue你来呀 \w/

**Comment by gaocegege** [comment]
我现在已经不能测试了。。

**Comment by laohyx** [comment]
那是非常地不好。毕竟是too young时写的。
建议把MVC分离一下 ～

在 2016-08-09 11:29:45，"Ce Gao" <notifications@github.com> 写道：


https://github.com/laohyx/electsys/blob/master/content_script/lesson.js#L706:#L708

可读性不是很好，应该有更好的方式吧

**Comment by zackszhu** [comment]
坐等重构，最好还能去jQuery化什么的

**Comment by laohyx** [comment]
有啥推荐吗？其实插件还是比较偏过程化的。把jQ用好，风格好些，也许还可以接受

在 2016-08-09 11:58:13，"zackszhu" <notifications@github.com> 写道：


坐等重构，最好还能去jQuery化什么的

**Comment by zackszhu** [comment]
re @laohyx 
比如换上es6标准，然后把ajax换成fetch api这样可以提高一点可读性把。
毕竟我不是专业的，js也懂的不多

**Comment by laohyx** [comment]
哦有道理！当然主要的问题还是代码写得太乱了。。

在 2016-08-09 12:06:30，"zackszhu" <notifications@github.com> 写道：


re @laohyx
比如换上es6标准，然后把ajax换成fetch api这样可以提高一点可读性把。
毕竟我不是专业的，js也懂的不多

**Comment by zackszhu** [comment]
re @laohyx 
可以参考一下这个https://github.com/yangfl/electsys--，好像是用了新的一套的，但是我记得我之前试的时候用不了？

**Comment by hczhcz** [comment]
个人不建议 ES6，考虑到还有很多旧版本浏览器存在

**Comment by zackszhu** [comment]
我觉得是chrome浏览器了一版都比较新的吧。。

**Comment by at15** [comment]
@zackszhu 这个真不一定，很多人chrome可能是百度到结果下的安装包，然后由于chrome无法自动更新，平时使用也不会什么问题，所以就一直在某个旧版本了。不过也可以用babel之类的把es6转到es5，但是这个项目没必要搞太复杂吧.....

**Comment by zackszhu** [comment]
@at15 好的吧

**Comment by ComMouse** [comment]
@zackszhu See this stat: http://kangax.github.io/compat-table/es6/

**Comment by gaocegege** [comment]
所以一步步来呗，先把这两个list整出去吧，看着好累

**Comment by ComMouse** [comment]
Also @ShieLian 有什么建议嘛

**Comment by ShieLian** [comment]
@ComMouse 一脸懵逼

**Comment by ComMouse** [comment]
现在除了选课部分比较乱基本都分离出来了……选课部分目前感觉有点困难，需要把交互优化、小课表、课程数据处理等等分开
